export const SYSTEM_CONFIG = {
  MODE: (process.env.SYSTEM_MODE || 'SIMULATION') as 'SIMULATION' | 'LICENSED_FIAT',
  CURRENCY_NAME: 'VERA',
  CURRENCY_SYMBOL: 'VERA',
  FIAT_PARITY: 1.0,
  WITHHOLDING_TAX_RATE: process.env.SYSTEM_MODE === 'LICENSED_FIAT' ? 0.20 : 0.00
};
